#!/usr/bin/env python
from __future__ import print_function

import rospy
import rs_odom_manager

if __name__ == '__main__':
    try:
        rs_odom_manager.start_manager()
    except rospy.ROSInterruptException:
        pass
